### ISSUE TITLE
Paloma: undefined controller -> Directions

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [kbparagua/paloma#67]
I haven't had the pleasure of this gem work for me at all. I can't figure out what I'm doing wrong!

**application.js**  
```javascript
//= require_tree ./application
//= require paloma
```

**app/assets/paloma/directions.js**
```ruby
var DirectionsController = Paloma.controller('Directions');
DirectionsController.prototype.index = function(){
  alert('Hello?');
};
```

**app/controllers/directions_controller.rb**
```ruby
class DirectionsController < ApplicationController
  def index
    respond_to :html
  end
end
```

It isn't clear in the README how the page-specific JS file is utilized/embedded into the final document, so I can't really say where this has gone awry.

Rails `v4.1`, Ruby `v2.1.5`

I have looked at [this SO question](http://stackoverflow.com/questions/16660849/rails-paloma-gem-how-to-load-page-specific-javascript) and noticed that the programmer seemed to be including his page-specific JS in the application.js file - which in my mind defeats the purpose of page-specific JS (as it causes bloat in the application.js file)...or maybe I'm missing something with how this gem works.

**Comment by JakeTheSnake3p0** [comment]
After some more searching it's as I feared...everything has to be included into a JS file that is served externally; the page-specific JS isn't inlined.

**Comment by kbparagua** [comment]
@JakeTheSnake3p0
The meaning of `page-specific JS` in Paloma's context is that a javascript code will **execute** depending on which page is loaded. It doesn't mean that a javascript file will be **included** or **loaded** when a specific page is loaded,  doing that will defeat the purpose of the Asset pipeline. Asset pipeline is merging all javascript files into one big file so that everything will be loaded at once and it will be cached by the server/client.

If you have any questions or if you need any assistance on using Paloma, feel free to ask. Thanks.
